apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme }}
    alb.ingress.kubernetes.io/subnets: {{ .Values.ingress.subnets }}
    alb.ingress.kubernetes.io/security-groups: {{ .Values.ingress.securityGroups }}
    alb.ingress.kubernetes.io/tags: scos.delete.on.teardown=true
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certificateARN }}
    alb.ingress.kubernetes.io/actions.redirect: '{"Type": "redirect", "RedirectConfig":{"Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
spec:
  backend:
    serviceName: {{ .Chart.Name }}
    servicePort: {{ .Values.service.port  }}
  rules:
  - host: cota.{{ .Values.ingress.rootDnsZone }}
    http:
      paths:
      - path: /*
        backend:
          serviceName: redirect
          servicePort: use-annotation
  - host: cota.{{ .Values.ingress.dnsZone }}
    http:
      paths:
      - path: /*
        backend:
          serviceName: redirect
          servicePort: use-annotation
  - http:
      paths:
      - path: /*
        backend:
          serviceName: redirect
          servicePort: use-annotation
